# Generated by Django 3.2.7 on 2021-09-30 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=10)),
                ('model', models.IntegerField(max_length=5, unique=True)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.product')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('speed', models.IntegerField(max_length=10)),
                ('ram', models.IntegerField(max_length=10)),
                ('hd', models.IntegerField(max_length=10)),
                ('cd', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.product')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('speed', models.IntegerField(max_length=10)),
                ('ram', models.IntegerField(max_length=10)),
                ('hd', models.IntegerField(max_length=10)),
                ('screen', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.product')),
            ],
        ),
    ]
