# Generated by Django 3.2.7 on 2021-09-30 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_auto_20210930_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('speed', models.IntegerField(max_length=10)),
                ('ram', models.IntegerField(max_length=10)),
                ('hd', models.IntegerField(max_length=10)),
                ('screen', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('speed', models.IntegerField(max_length=10)),
                ('ram', models.IntegerField(max_length=10)),
                ('hd', models.IntegerField(max_length=10)),
                ('cd', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('maker', models.CharField(max_length=10)),
                ('model', models.IntegerField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='b',
            name='b',
        ),
        migrations.RemoveField(
            model_name='c',
            name='c',
        ),
        migrations.DeleteModel(
            name='A',
        ),
        migrations.DeleteModel(
            name='B',
        ),
        migrations.DeleteModel(
            name='C',
        ),
        migrations.AddField(
            model_name='printer',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.product'),
        ),
        migrations.AddField(
            model_name='pc',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.product'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.product'),
        ),
    ]
